spring:
  datasource:
    url: jdbc:mysql://192.168.228.128:3306/spring-cache?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.228.128


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    edu.hust.cache.mapper: debug